# [timestamp]
# format = 

# [loglevel]
# debug = ["DEBUG"]
# info = ["INFO"]

[[fields]]
name = "Timestamp"
type = "timestamp"
width = 8

[[fields]]
name = "Level"
type = "loglevel"
width = 6

[[fields]]
name = "Msg"
type = "string"
width = 10
flex = true

[[fields]]
name = "Host"
type = "string"
width = 10

# [parser]
# parserType = "json"
#
# [[parser.json.fields]]
# jsonKey = "Timestamp"
# type = "timestamp"
#
# [[parser.json.fields]]
# jsonKey = "Level"
# type = "loglevel"
#
# [[parser.json.fields]]
# jsonKey = "Msg"
# type = "string"
#
# [[parser.json.fields]]
# jsonKey = "Host"
# type = "string"

[parser]
parserType = "regex"

[parser.regex]
regex = '\[(?P<Timestamp>.*)\] \[(?P<Level>\w+)\] (?P<Msg>.*)'

[[parser.regex.fields]]
name = "Timestamp"
type = "timestamp"

[[parser.regex.fields]]
name = "Level"
type = "loglevel"

[[parser.regex.fields]]
name = "Msg"
type = "string"
